repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.9
  hooks:
    - id: ruff
      args: ["--fix"]
      exclude: ^(tests/|deps/)
    - id: ruff-format
      exclude: ^(tests/|deps/)
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black
      exclude: ^(tests/|deps/)
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
    - id: detect-secrets
      exclude: ^(tests/|deps/)
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      exclude: ^(tests/|deps/|\.venv/)
