name: Autofix

on:
  push:
    branches:
      - hardening/roadmap-v1
  workflow_dispatch:

jobs:
  autofix:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set UTF-8 encoding
        run: |
          echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
          echo "LC_ALL=C.UTF-8" >> $GITHUB_ENV
          echo "LANG=C.UTF-8" >> $GITHUB_ENV

      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort

      - name: Run ruff --fix
        run: ruff check . --fix
        continue-on-error: true

      - name: Run black
        run: black .
        continue-on-error: true

      - name: Run isort
        run: isort .
        continue-on-error: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "autofix: ruff --fix, black, isort"
        continue-on-error: true

      - name: Verify ruff
        run: ruff check .
        continue-on-error: true
